<html>
  <head>
    <title>Alta de Tarea</title>
  </head>

  <body>
    <form action="/web/taskup" method="post">
    titulo:<input name="titulo" type="text"><br>
    descripcion:<textarea name="descripcion" type="text"></textarea><br>
    estado:<input name="estado" type="text"><br>
    </select><br>
    hora_inicio:<input name="hora_inicio" type="datetime-local"><br>
    hora_fin:<input name="hora_fin" type="datetime-local"><br>
    <input type="submit" value="Enviar">
    </form>
  </body>



</html>