<?php
  $task = $this->_data["_data"];

  $countTask = count($task);

?>

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Home</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>

<body class="bg-gray-100">

<header>
        <nav class="bg-white border-gray-200 px-4 lg:px-6 py-2.5 dark:bg-gray-800">
            <div class="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl">

                <div class="flex items-center lg:order-2">
                    <a href="/web/" class="text-gray-800 dark:text-white hover:bg-gray-50 focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-4 lg:px-5 py-2 lg:py-2.5 mr-2 dark:hover:bg-gray-700 focus:outline-none dark:focus:ring-gray-800">Log out</a>
                    <a href="/web/user" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-4 lg:px-5 py-2 lg:py-2.5 mr-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Modificar usuario</a>
                    <button data-collapse-toggle="mobile-menu-2" type="button" class="inline-flex items-center p-2 ml-1 text-sm text-gray-500 rounded-lg lg:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="mobile-menu-2" aria-expanded="false">
                        <span class="sr-only">Open main menu</span>
                        <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
                        <svg class="hidden w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                    </button>
                </div>
                <div class="hidden justify-between items-center w-full lg:flex lg:w-auto lg:order-1" id="mobile-menu-2">
                    <ul class="flex flex-col mt-4 font-medium lg:flex-row lg:space-x-8 lg:mt-0">
                        <li>
                            <a href="#" class="block py-2 pr-4 pl-3 text-white rounded bg-blue-700 lg:bg-transparent lg:text-blue-700 lg:p-0 dark:text-white" aria-current="page">Home</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
</header>

<?php
// include '/web/app/layout/header';
?>

      <!-- This is an example component -->
      <div class="max-w-2xl mx-auto">
        <div class="relative bg-gray-200 overflow-x-auto border-black shadow-md sm:rounded-lg my-10 
        text-sm font-medium text-lg text-gray-500 dark:text-gray-300 flex flex-col text-center ">
        <div class="p-4"><h1 class=>Listado de tareas</h1> </div>
        <div class="p-4 self-center"><img src="https://cdn-icons-png.flaticon.com/512/3789/3789946.png" class="mr-3 h-6 sm:h-9 " alt="Flowbite Logo" />
        </div>
      </div>
        <div class="relative bg-gray-200 overflow-x-auto border-black shadow-md sm:rounded-lg my-10">
          <div class="p-4">
            <label for="table-search" class="sr-only">Search</label>
            <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
              <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                <tr>
                  <th scope="col" class="p-4">
                  </th>
                  <th scope="col" class="px-6 py-3">
                    Título
                  </th>
                  <th scope="col" class="px-6 py-3">
                    Descripcion
                  </th>
                  <th scope="col" class="px-6 py-3">
                    Estado
                  </th>
                  <th scope="col" class="px-6 py-3">
                    Fecha Inicio
                  </th>
                  <th scope="col" class="px-6 py-3">
                    Fecha fin
                  </th>

                  <th scope="col" class="px-6 py-3">
                    <span class="sr-only">Edit</span>
                  </th>
                </tr>
              </thead>
              <tbody>
                <?php  
                for ($i = 0; $i <= ($countTask -1); $i++) {
                  $contador = $i;
                  
                ?>
                <tr
                  class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                  <?php $contador2 = $contador;?> 
                  <td class="w-4 p-4">
                  </td>
                  <th scope="row" class="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap">
                   <?php  echo $task[$i]["titulo"];  ?>   
                  </th>
                  <td class="px-6 py-4">
                  <?php  echo $task[$i]["descripcion"]; ?>
                  </td>
                  <td class="px-6 py-4">
                  <?php  echo $task[$i]["estado"];?>    
                  </td>
                  <td class="px-6 py-4">
                  <?php  echo $task[$i]["hora_inicio"];?>  
                  </td>
                  <td class="px-6 py-4">
                  <?php  echo $task[$i]["hora_fin"];?>  
                  </td>
                 
                  <td class="px-6 py-4 text-right">
                    <a  href="/web/taskedithome"  class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Edit <?php echo $contador2;
                    $_SESSION["taskPosition"] = $contador2; ?></a>
                  </td>

                  <?php
                  }
                  ?>
                </tr>
              </tbody>
            </table>
          </div>
          <div clas="mt-5">
            <div class="text-sm font-medium text-lg text-gray-500 dark:text-gray-300 py-5 px-5 text-right">

              <a href="/web/taskhome" class="text-blue-700 hover:underline dark:text-blue-500">+ Añadir tarea</a>
            </div>


          </div>

        </div>

</body>

</html>
