<!DOCTYPE html>

<?php 


?>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Loguin</title>
</head>
<body>

<section class="index-login">
    <div class="index-login-loguin">
            <h4>WRONG PASWORD!</h4>
            <P>Try it again!</P>
            <form action="/web/" method="POST">       
                <br>
                <button type="submit" name="submit">GO!</button>
            </form>
        </div>
    </div>
</section>
    
</body>
</html>