<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>signup</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <!-- basado en https://tailwindcomponents.com/component/input-field -->
</head>

<body class="bg-gray-100">
    <section>
        <div class="max-w-2xl mx-auto my-16 bg-white px-10 py-5">
            <h1 class="text-xl font-medium text-gray-900 dark:text-white py-5">Create account</h1>

            <form action="/web/signup" method="POST">
                <div class="grid gap-6 mb-6 lg:grid-cols-2">
                    <div>
                        <label for="name"
                            class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Name</label>
                        <input type="text" id="name" name="name"
                            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                            placeholder="Name" required>
                    </div>
                    <div>
                        <label for="surname"
                            class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Surname</label>
                        <input type="text" id="surname" name="surname"
                            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                            placeholder="Surname" required>
                    </div>
                </div>
                <div class="mb-6">
                    <label for="userName"
                        class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Username</label>
                    <input type="text" id="userName" name="userName"
                        class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                        placeholder="Username" required>
                </div>
                <div class="mb-6">
                    <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Email
                        address</label>
                    <input type="email" id="email" name="email"
                        class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                        placeholder="email@email.com" required>
                </div>
                <div class="mb-6">
                    <label for="password"
                        class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Password</label>
                    <input type="password" id="password" name="pw"
                        class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                        placeholder="•••••••••" required>
                </div>
                <button type="submit" name="submit"
                    class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Submit</button>

            </form>
            <div class="text-sm font-medium text-gray-500 dark:text-gray-300 py-5 text-right">
                    Are you registered? 
                    <a href="/web"
                        class="text-blue-700 hover:underline dark:text-blue-500" >Login</a>
                </div>
        </div>

    </section>

        <!--
            <div class="index-login-signup">
                    <h4>SING UP</h4>
                    <P>Don't have an account yet? Sing up here!</P>
                    <form action="/web/signup" method="POST">
                        <input type="text" name="name" placeholder="name">
                        <input type="text" name="surname" placeholder="surname">
                        <input type="text" name="userName" placeholder="userName">
                        <input type="text" name="email" placeholder="email">
                        <input type="password" name="pw" placeholder="pw">
                        <br>
                        <button type="submit" name="submit">SING UP</button>
                    </form>
                </div>
            </div>
            -->

</body>

</html>