<!DOCTYPE html>

<?php //require("../../../app/models/login.class.php"); 


?>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Loguin</title>
</head>
<body>

<section class="index-login">
    <div class="index-login-loguin">
            <h4>LOGIN</h4>
            <P>Don't have an account yet? Sing up here!</P>
            <form action= <?php //$this->login(); ?> method="POST">
                <input type="text" name="username" placeholder="Username">
                <input type="password" name="pwd" placeholder="Password">
                <br>
                <button type="submit" name="submit">LOG IN</button>
            </form>
        </div>
    </div>
</section>
    
</body>
</html>