
<?php include ROOT_PATH.'/app/views/layouts/header.php';?>

<?php
  $user = $this->_user;
?>

  <!-- <body>
    <form action="/web/modifyuser" method="POST">
    Name:<input name="newname" type="text" placeholder=<?php //echo $user['name'];?> ><br>
    Surname<input name="newsurname" type="text" placeholder=<?php //echo $user['surname'];?>><br>
    Username:<input name="newusername" type="text" placeholder=<?php //echo $user['userName'];?>><br>
    E-mail:<input name="newemail" type="text" placeholder=<?php //echo $user['email'];?>><br>
    Password:<input name="newpasword" type="password" placeholder=<?php //echo $user['pw'];?>><br>
  
    </select><br>
    <input type="submit" value="Enviar">
    </form>
    <form action="/web/deleteuser" method="POST">
    </select><br>
    <input type="submit" value="Delete user">
  </body> -->

  <body class="bg-gray-100">
    <section>
        <div class="max-w-2xl mx-auto my-16 bg-white px-10 py-5">
            <h1 class="text-xl font-medium text-gray-900 dark:text-white py-5">Modify user</h1>

            <form action="/web/modifyuser" method="POST">
                <div class="grid gap-6 mb-6 lg:grid-cols-2">
                    <div>
                        <label for="name"
                            class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Name</label>
                        <input type="text" id="name" name="name"
                            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                            placeholder="<?php echo $user['name'];?>">
                    </div>
                    <div>
                        <label for="surname"
                            class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Surname</label>
                        <input type="text" id="surname" name="surname"
                            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                            placeholder="<?php echo $user['surname'];?>">
                    </div>
                </div>
                <div class="mb-6">
                    <label for="userName"
                        class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Username</label>
                    <input type="text" id="userName" name="userName"
                        class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                        placeholder="<?php echo $user['userName'];?>">
                </div>
                <div class="mb-6">
                    <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Email
                        address</label>
                    <input type="email" id="email" name="email"
                        class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                        placeholder="<?php echo $user['email'];?>">
                </div>
                <div class="mb-6">
                    <label for="password"
                        class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Password</label>
                    <input type="password" id="password" name="pw"
                        class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                        placeholder="<?php echo $user['pw'];?>">
                </div>
                <button type="submit" name="submit"
                    class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Submit</button>
            </form>
            <form action="/web/deleteuser" method="POST" class="py-3">
            <button type="submit" name="deleteuser" value="deleteuser"
                    class="text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-800">deleteuser</button>
            </form>

            <div class="text-sm font-medium text-gray-500 dark:text-gray-300 py-5 text-right">
                    <a href="/web/home"
                        class="text-blue-700 hover:underline dark:text-blue-500" >Volver al listado de tareas</a>
            </div>
        </div>

    </section>

</body>

</html>
